[package]
name = "string_to_Unicode_codepoint"
version = "0.1.0"
authors = ["Unbewohnte <https://github.com/Unbewohte>"]
edition = "2018"
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
